export const movie_list = [
  {
    _id: 1,
    title: "Happy Birthday to Me",
    genre: "horrorGenre",
    numberInStock: 79,
    dailyRentalRate: 50,
    publishDate: "1/29/2020",
    liked: true,
  },
  {
    _id: 2,
    title: "Great Yokai War, The (Yôkai daisensô)",
    genre: "adventureGenre",
    numberInStock: 37,
    dailyRentalRate: 90,
    publishDate: "2/20/2020",
    liked: true,
  },
  {
    _id: 3,
    title: "Waterboys",
    genre: "comedyGenre",
    numberInStock: 16,
    dailyRentalRate: 29,
    publishDate: "12/13/2019",
    liked: false,
  },
  {
    _id: 4,
    title: "Stella Street",
    genre: "comedyGenre",
    numberInStock: 87,
    dailyRentalRate: 65,
    publishDate: "2/13/2020",
    liked: false,
  },
  {
    _id: 5,
    title: "Wrong Turn 2: Dead End",
    genre: "actionGenre",
    numberInStock: 55,
    dailyRentalRate: 40,
    publishDate: "4/3/2020",
    liked: false,
  },
  {
    _id: 6,
    title: "New York Confidential",
    genre: "crimeGenre",
    numberInStock: 95,
    dailyRentalRate: 30,
    publishDate: "10/18/2019",
    liked: false,
  },
  {
    _id: 7,
    title: "Nocturna",
    genre: "adventureGenre",
    numberInStock: 21,
    dailyRentalRate: 6,
    publishDate: "10/28/2019",
    liked: false,
  },
  {
    _id: 8,
    title: "3rd Voice, The",
    genre: "crimeGenre",
    numberInStock: 51,
    dailyRentalRate: 16,
    publishDate: "1/26/2020",
    liked: true,
  },
  {
    _id: 9,
    title: "Black Moon",
    genre: "horrorGenre",
    numberInStock: 8,
    dailyRentalRate: 66,
    publishDate: "3/26/2020",
    liked: true,
  },
  {
    _id: 10,
    title: "The Tomb",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 11,
    title: "Harry Potter and The Deathly Hallows",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: true,
  },
  {
    _id: 12,
    title: "Ring 1",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 13,
    title: "Ring 2",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 14,
    title: "Bangalore Days",
    genre: "adventureGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 15,
    title: "Deadpool",
    genre: "comedyGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 16,
    title: "Finding Nemo",
    genre: "adventureGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 17,
    title: "Wall-E",
    genre: "adventureGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 18,
    title: "The Tomb 1",
    genre: "comedyGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 19,
    title: "The Tomb 2",
    genre: "comedyGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 20,
    title: "The Tomb 3",
    genre: "crimeGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 21,
    title: "The Tomb 4",
    genre: "crimeGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 22,
    title: "ScaryMovie",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 23,
    title: "Ring 2",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 24,
    title: "Lord of the Rings",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
  {
    _id: 25,
    title: "Saw",
    genre: "horrorGenre",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
    liked: false,
  },
];
