export const movie_list = [
  {
    _id: 1,
    title: "Happy Birthday to Me",
    genre: "Horror",
    numberInStock: 79,
    dailyRentalRate: 50,
    publishDate: "1/29/2020",
  },
  {
    _id: 2,
    title: "Great Yokai War, The (Yôkai daisensô)",
    genre: "Adventure",
    numberInStock: 37,
    dailyRentalRate: 90,
    publishDate: "2/20/2020",
  },
  {
    _id: 3,
    title: "Waterboys",
    genre: "Comedy",
    numberInStock: 16,
    dailyRentalRate: 29,
    publishDate: "12/13/2019",
  },
  {
    _id: 4,
    title: "Stella Street",
    genre: "Comedy",
    numberInStock: 87,
    dailyRentalRate: 65,
    publishDate: "2/13/2020",
  },
  {
    _id: 5,
    title: "Wrong Turn 2: Dead End",
    genre: "Action",
    numberInStock: 55,
    dailyRentalRate: 40,
    publishDate: "4/3/2020",
  },
  {
    _id: 6,
    title: "New York Confidential",
    genre: "Crime",
    numberInStock: 95,
    dailyRentalRate: 30,
    publishDate: "10/18/2019",
  },
  {
    _id: 7,
    title: "Nocturna",
    genre: "Adventure",
    numberInStock: 21,
    dailyRentalRate: 6,
    publishDate: "10/28/2019",
  },
  {
    _id: 8,
    title: "3rd Voice, The",
    genre: "Crime",
    numberInStock: 51,
    dailyRentalRate: 16,
    publishDate: "1/26/2020",
  },
  {
    _id: 9,
    title: "Black Moon",
    genre: "Horror",
    numberInStock: 8,
    dailyRentalRate: 66,
    publishDate: "3/26/2020",
  },
  {
    _id: 10,
    title: "The Tomb",
    genre: "Horror",
    numberInStock: 6,
    dailyRentalRate: 70,
    publishDate: "2/22/2020",
  },
];
